# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - akulmmm@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

    env:
      global:
       - CODECOV_TOKEN="b47eb3d5-b4fc-4ff1-8ea2-fc30224a6d5c"
